'use strict';

const { contextBridge, ipcRenderer, webFrame, webUtils } = require('electron');

function on(channel, callback) {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('eagleMV', {
  platform: process.platform,
  // What this client can do locally. The web shim serves the same surface
  // with the host-bound entries set to false so the renderer hides them.
  capabilities: {
    nativeDrag: true,
    hostDialogs: true,
    clipboardFiles: true,
    finder: true,
    openDefault: true,
    openOther: true,
    share: true,
    export: true,
    importLocal: true,
    customThumbnail: true,
    copyPath: true,
    uiZoom: true,
    webAccess: true
  },
  mediaURL: (kind, id) => `eaglemv://${kind}/${encodeURIComponent(String(id))}`,
  connect: () => ipcRenderer.invoke('hub:connect'),
  getLibraryHistory: () => ipcRenderer.invoke('library:history'),
  switchLibrary: data => ipcRenderer.invoke('library:switch', data),
  identity: () => ipcRenderer.invoke('hub:identity'),
  query: query => ipcRenderer.invoke('hub:query', query),
  getRecentFolders: () => ipcRenderer.invoke('hub:recent-folders'),
  getTrashItems: data => ipcRenderer.invoke('hub:trash-items', data),
  getItem: id => ipcRenderer.invoke('hub:get-item', id),
  getComments: data => ipcRenderer.invoke('item:comments', data),
  addComment: data => ipcRenderer.invoke('item:add-comment', data),
  updateComment: data => ipcRenderer.invoke('item:update-comment', data),
  removeComment: data => ipcRenderer.invoke('item:remove-comment', data),
  setCustomThumbnail: data => ipcRenderer.invoke('item:set-custom-thumbnail', data),
  getTags: () => ipcRenderer.invoke('hub:tags'),
  getTagGroups: () => ipcRenderer.invoke('hub:tag-groups'),
  createSmartFolder: data => ipcRenderer.invoke('smart-folder:create', data),
  updateSmartFolder: data => ipcRenderer.invoke('smart-folder:update', data),
  removeSmartFolder: data => ipcRenderer.invoke('smart-folder:remove', data),
  mutate: mutation => ipcRenderer.invoke('hub:mutate', mutation),
  mutateSet: mutation => ipcRenderer.invoke('hub:mutate-set', mutation),
  watchItems: ids => ipcRenderer.invoke('hub:watch-items', ids),
  newWindow: data => ipcRenderer.invoke('window:new', data || null),
  initialWindowState: () => ipcRenderer.invoke('window:initial-state'),
  focusWindow: () => ipcRenderer.invoke('window:focus'),
  isFullScreen: () => ipcRenderer.invoke('window:is-fullscreen'),
  setZoomFactor: factor => webFrame.setZoomFactor(Number(factor)),
  confirmClose: () => ipcRenderer.send('window:confirm-close'),
  cancelClose: () => ipcRenderer.send('window:cancel-close'),
  createFolder: data => ipcRenderer.invoke('folder:create', data),
  createDocument: data => ipcRenderer.invoke('document:create', data),
  mutateFolder: data => ipcRenderer.invoke('folder:mutate', data),
  markFolderUsed: data => ipcRenderer.send('folder:used', data),
  importItems: data => ipcRenderer.invoke('items:import', data),
  importClipboard: data => ipcRenderer.invoke('items:import-clipboard', data),
  pathForFile: file => webUtils.getPathForFile(file),
  showInFinder: id => ipcRenderer.invoke('item:show-in-finder', id),
  filePath: id => ipcRenderer.invoke('item:file-path', id),
  fileURL: id => ipcRenderer.invoke('item:file-url', id),
  readMetadata: id => ipcRenderer.invoke('item:metadata', id),
  openDefault: id => ipcRenderer.invoke('item:open-default', id),
  exportFiles: data => ipcRenderer.invoke('items:export', data),
  openOther: data => ipcRenderer.invoke('items:open-other', data),
  shareFiles: data => ipcRenderer.invoke('items:share', data),
  duplicateFiles: data => ipcRenderer.invoke('items:duplicate', data),
  copyFiles: ids => ipcRenderer.invoke('clipboard:write-files', ids),
  copyText: text => ipcRenderer.invoke('clipboard:write-text', String(text || '')),
  logError: entry => ipcRenderer.send('log:renderer-error', entry),
  openExternal: url => ipcRenderer.invoke('shell:open-external', String(url || '')),
  startDrag: data => ipcRenderer.send('item:start-drag', data),
  cancelDrag: token => ipcRenderer.send('item:cancel-drag', token),
  getPins: data => ipcRenderer.invoke('pins:get', data),
  setPins: data => ipcRenderer.invoke('pins:set', data),
  readText: data => ipcRenderer.invoke('text:read', data),
  saveText: data => ipcRenderer.invoke('text:save', data),
  onStatus: callback => on('hub:status', callback),
  onLibraryChanged: callback => on('hub:library-changed', callback),
  onItemsChanged: callback => on('hub:items-changed', callback),
  onQueryInvalidated: callback => on('hub:query-invalidated', callback),
  onTrashSelection: callback => on('command:trash-selection', callback),
  onPinSelection: callback => on('command:pin-selection', callback),
  onAddToFolder: callback => on('command:add-to-folder', callback),
  onMoveToFolder: callback => on('command:move-to-folder', callback),
  onRemoveFromFolder: callback => on('command:remove-from-folder', callback),
  onAddTag: callback => on('command:add-tag', callback),
  onSetRating: callback => on('command:set-rating', callback),
  onSetTagColor: callback => on('command:set-tag-color', callback),
  onRenameRequest: callback => on('command:rename', callback),
  getTagColors: data => ipcRenderer.invoke('tag-colors:get', data),
  setTagColor: data => ipcRenderer.invoke('tag-colors:set', data),
  renameTag: data => ipcRenderer.invoke('tag:rename', data),
  mergeTag: data => ipcRenderer.invoke('tag:merge', data),
  createTagGroup: data => ipcRenderer.invoke('tag-group:create', data),
  updateTagGroup: data => ipcRenderer.invoke('tag-group:update', data),
  removeTagGroup: data => ipcRenderer.invoke('tag-group:remove', data),
  addTagsToGroup: data => ipcRenderer.invoke('tag-group:add-tags', data),
  removeTagsFromGroup: data => ipcRenderer.invoke('tag-group:remove-tags', data),
  getWebAccess: () => ipcRenderer.invoke('web-access:get'),
  setWebAccess: data => ipcRenderer.invoke('web-access:set', data),
  resetWebAccessKey: () => ipcRenderer.invoke('web-access:reset-key'),
  onWebAccessRequest: callback => on('command:web-access', callback),
  onImportRequest: callback => on('command:import', callback),
  onCreateFolderRequest: callback => on('command:create-folder', callback),
  onCreateDocumentRequest: callback => on('command:create-document', callback),
  onCreateSmartFolderRequest: callback => on('command:create-smart-folder', callback),
  onPinsChanged: callback => on('pins:changed', callback),
  onTagDataChanged: callback => on('tag-data:changed', callback),
  onFolderUsed: callback => on('folder:used', callback),
  onTextChanged: callback => on('text:changed', callback),
  onItemDragState: callback => on('item:drag-state', callback),
  onDragFinished: callback => on('item:drag-finished', callback),
  onRequestClose: callback => on('command:request-close', callback),
  onChromeState: callback => on('window:chrome-state', callback)
});
